server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost/powerup
    username: root
    password: sasa
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"